version: '3.4'
services:
  bull-queue-express:
    build:
      context: .
      target: base
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    command: yarn start:dev

  redis:
    image: redis
